name: iabd_plantilla
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26
  - pandas=2.2
  - matplotlib=3.8
  - seaborn=0.13
  - scikit-learn=1.4
  - jupyterlab
  - pip
  - pip:
      - requests==2.31.0
